#ifndef HW01_ORIENTEERING_EXITCODES_H_
#define HW01_ORIENTEERING_EXITCODES_H_

#define O_SUCCESS 0
#define O_UNEXPECTED_NULL_ARG 1
#define O_DAMAGED_DATA 2
#define O_BAD_ALLOC 3

#endif  // HW01_ORIENTEERING_EXITCODES_H_
