#ifndef HW02_MATCHES_EXITCODES_H_
#define HW02_MATCHES_EXITCODES_H_

#define EXIT_SUCCESS_ 0
#define EXIT_BAD_ALLOC_ 1
#define EXIT_INPUT_ERROR_ 2
#define EXIT_UNEXPECTED_NULL_ARG_ 3
#define EXIT_OPENDIR_ERROR_ 4
#define EXIT_OPENFILE_ERROR_ 5
#define EXIT_3RDPTY_ERROR_ 6

#endif  // HW02_MATCHES_EXITCODES_H_
