#ifndef PARKMAIL_HW_COLLECTIONS_EXITCODES_H_
#define PARKMAIL_HW_COLLECTIONS_EXITCODES_H_

#define PHWC_EXIT_SUCCESS 0
#define PHWC_EXIT_NULL_ARG 1
#define PHWC_EXIT_BAD_ALLOC 2

#endif  // PARKMAIL_HW_COLLECTIONS_EXITCODES_H_
