#ifndef PARKMAIL_HW_COLLECTIONS_RETURNCODES_H_
#define PARKMAIL_HW_COLLECTIONS_RETURNCODES_H_

#define COLLECTIONS_SUCCESS 0
#define COLLECTIONS_NULLARG_ERROR 1
#define COLLECTIONS_ALLOC_ERROR 2

#endif  // PARKMAIL_HW_COLLECTIONS_RETURNCODES_H_
