name: Homework01 CI
on:
  push:
    branches:
      - hw01
      - master
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install tools and dependencies
        run: |
          sudo apt install build-essential
          sudo apt install git
          sudo apt install lcov
          sudo apt install valgrind
          sudo apt install clang-tidy
          sudo apt install libgtest-dev
      - name: Build
        run: |
          cd homework01
          mkdir build && cd build
          cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          make
      - name: Lint
        run: |
          cd homework01/build
          run-clang-tidy "../*" -p . > report-linter.txt
      - name: Unit tests
        run: |
          cd homework01/build
          ./tests/test
      - name: Memory check
        run: |
          cd homework01/build
          valgrind \
            --tool=memcheck --leak-check=full \
            --show-leak-kinds=all --undef-value-errors=no \
            --verbose --log-file=report-valgrind.txt \
            -- ./tests/test
      - name: Coverage
        run: |
          cd homework01/build
          lcov -t "homework01" -o homework01.info -c -d .
          lcov --extract homework01.info "*/homework01/orienteering/*" -o homework01.info
          genhtml -o report-coverage.html homework01.info
      - name: Archive linter report
        uses: actions/upload-artifact@v2
        with:
          name: report-linter
          path: homework01/build/report-linter.txt
      - name: Archive valgrind report
        uses: actions/upload-artifact@v2
        with:
          name: report-valgrind
          path: homework01/build/report-valgrind.txt
      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: report-coverage
          path: homework01/build/report-coverage.html
